time_unit: 60
sim_loop:
  duration: 180
world:
  width: 25
  height: 50
  vegetation:
    classes: default/vegetation.yml
    builder: default/vegetation_builder.yml
  flora:
    classes: default/flora.yml
    builder: default/flora_builder.yml
  fauna:
    classes: default/animal.yml
    builder: default/fauna_builder.yml
dropzones:
  bot_1:
    from:  0
    to:   19
  gateway:
    from: 20
    to:   39
  transit:
    from: 50
    to:   49
  players:
    from: 60
    to:   79
  bot_2:
    from: 80
    to:   99
